FROM golang:1.22-alpine3.19 AS builder

# Install necessary tools
RUN apk add --no-cache build-base

# Set working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Enable CGO
ENV CGO_ENABLED=1

# Download dependencies
RUN go mod download

# Build the Tornjak Manager binary
RUN go build -mod=vendor -ldflags '-s -w -linkmode external -extldflags "-static"' -o bin/tornjak-manager ./cmd/manager/main.go

# Final runtime image
FROM alpine:3.19

# Create a working directory
RUN mkdir -p /opt/tornjak

# Copy the compiled binary
COPY --from=builder /app/bin/tornjak-manager /opt/tornjak/tornjak-manager

# Run the Tornjak Manager
ENTRYPOINT ["/opt/tornjak/tornjak-manager"]
